### ISSUE TITLE
cron-farm.js focusing on weakening a nonsensical choice of server.

### ISSUE THREAD

**Issue by TaiGambol** [whiskeyfur/bitburner-os#2]
**Describe the bug**
At some point, unclear what precisely, the cron-farm.js script shifts its target to 'fulcrumassets', a server far beyond anything I can actually hack, and stops hacking lower-level servers, likely due to lack of total RAM.

**To Reproduce**
1. Ensure you are not on a Bitnode, and have hacking ~750 and ~60,000GB of combined RAM available.
2. Killall and run cmd-purge.js
3. Run cron-farm.js
4. Observe all available server space gets dedicated to weakening 'fulcrumassets', despite 'fulcrumassets' being a level 1541 server and far out of reach of actually being hacked, and despite having lower-level servers fully grown and ready to hack.

**Expected behavior**
cron-farm.js should be hacking, growing, and weakening actually available servers as a priority, and only putting spare cycles towards unhackable servers at most, and probably not prioritizing something nearly 800 skill levels ahead when closer options are available.

**Screenshots**
https://i.imgur.com/ZIAePvH.png

https://i.imgur.com/fHGmZI6.png

**Comment by TaiGambol** [comment]
Update. It's -still- focusing on 'fulcrumassets' even after a fresh aug, despite having 2 hack and no access to the server. https://i.imgur.com/0BE0h8X.png

**Comment by TaiGambol** [comment]
I think I found the problem - line 22 was commented out, and that was the one filtering for 'can we actually hack this?' Can't confirm, because now I'm running into a different error about 'jcw is not defined', but.

**Comment by whiskeyfur** [comment]
(Believed to be) resolved with the latest rounds of updates.

reinstall the scripts and ensure that the cron-farm is enabled with 
run startup.js
run cmd-env.js set cron.farm true
