### ISSUE TITLE
cron-farm.js failing silently before distributing workers or printing server targets

### ISSUE THREAD

**Issue by TaiGambol** [whiskeyfur/bitburner-os#3]
**Describe the bug**
'cron-farm.js' fails silently and hangs indefinitely. Inserting debug print() messages narrowed the failure point down to around line 61, where the server loop attempts to print the target's hack/grow/weaken threads needed.

**To Reproduce**
1. From a fresh aug/bitnode, run cron-farm.js
2. tail cron-farm.js
3. Observe the server names and details fail to print
4. nano cron-farm.js
5. Comment out lines 6 and 7 that prevent logging to the tail window.
6. kill and re-run cron-farm.js
7. Observe the script run through checking all of the server details, fail to print it as directed, and skip straight to the 'sleep' command around line 92, and stay asleep long past its timer.

**Expected behavior**
For cron-farm.js to cycle through the available servers, list their needed threads for hack/grow/weaken, and then distribute attack threads to the various servers as needed.

**Additional context**
My best guess is it's something to do with the 'incomePerSec()' call - up higher, there's a sort for 'jcw.incomePerSec()' which fails, and continues failing if I delete the leading 'jcw.' from it. Commenting it out allows the script to proceed to the point described above.

**Comment by whiskeyfur** [comment]
(Believed to be) resolved with the latest rounds of updates.

reinstall the scripts and ensure that the cron-farm is enabled with 
run startup.js
run cmd-env.js set cron.farm true
